//Approved 12/29/2022 10:56PM
[assembly: System.Reflection.AssemblyCompany("RandomiaGaming")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © RandomiaGaming 2022")]
[assembly: System.Reflection.AssemblyDefaultAlias("MysteryHelper")]
[assembly: System.Reflection.AssemblyDescription("A collection of useful helper methods. A dependency for MysteryMemeware, MysteryInstaller, and MysteryUninstaller.")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFlags(System.Reflection.AssemblyNameFlags.None)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyProduct("MysteryHelper")]
[assembly: System.Reflection.AssemblyTitle("MysteryHelper")]
[assembly: System.Reflection.AssemblyTrademark("Trademark ™ RandomiaGaming 2022")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]