[assembly: System.Reflection.AssemblyCompany("FinlayTheBerry")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © FinlayTheBerry 2022")]
[assembly: System.Reflection.AssemblyDefaultAlias("Cosmic Cats Installer")]
[assembly: System.Reflection.AssemblyDescription("An open source run and jump adventure game about cats in space!")]
[assembly: System.Reflection.AssemblyFileVersion("1.0")]
[assembly: System.Reflection.AssemblyFlags(System.Reflection.AssemblyNameFlags.None)]
[assembly: System.Reflection.AssemblyInformationalVersion("Memeware that plays the song \"It's a mystery\" forever. To uninstall hold escape for 10 seconds.")]
[assembly: System.Reflection.AssemblyProduct("Cosmic Cats Installer")]
[assembly: System.Reflection.AssemblyTitle("Cosmic Cats Installer")]
[assembly: System.Reflection.AssemblyTrademark("Trademark ™ FinlayTheBerry 2022")]
[assembly: System.Reflection.AssemblyVersion("1.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]