[assembly: System.Reflection.AssemblyCompany("RandomiaGaming")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © RandomiaGaming 2022")]
[assembly: System.Reflection.AssemblyDefaultAlias("Cosmic Cats Installer")]
[assembly: System.Reflection.AssemblyDescription("An open source run and jump adventure game about cats in space!")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFlags(System.Reflection.AssemblyNameFlags.None)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyProduct("Cosmic Cats Installer")]
[assembly: System.Reflection.AssemblyTitle("Cosmic Cats Installer")]
[assembly: System.Reflection.AssemblyTrademark("Trademark ™ RandomiaGaming 2022")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]