[assembly: System.Reflection.AssemblyCompany("RandomiaGaming")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © RandomiaGaming 2022")]
[assembly: System.Reflection.AssemblyDefaultAlias("MysteryUninstaller")]
[assembly: System.Reflection.AssemblyDescription("An uninstaller for MysteryMemeware. Depends upon MysteryHelper. Reqires administrator to execute.")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFlags(System.Reflection.AssemblyNameFlags.None)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyProduct("MysteryUninstaller")]
[assembly: System.Reflection.AssemblyTitle("MysteryUninstaller")]
[assembly: System.Reflection.AssemblyTrademark("Trademark ™ RandomiaGaming 2022")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]